### ISSUE TITLE
However chain codes can also take structs as the arguments instead for using just a list of variables.

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger/fabric-chaincode-go#101]
ref to https://github.com/Hyperledger-TWGC/tape/issues/377
it seems chaincode now supports structs, does it implemented with golang?
> However chain codes can also take structs as the arguments instead for using just a list of variables.

**Comment by denyeart** [comment]
Chaincodes written with Go contract api can take struct arguments. Client would pass as JSON and the contract serializer will convert to the struct.
See doc at https://github.com/hyperledger/fabric-contract-api-go/blob/main/tutorials/managing-objects.md
