### ISSUE TITLE
ShimTest will be removed in a future release. Future development should make use of the ChaincodeStub Interface for generating mocks

### ISSUE THREAD

**Issue by hxx258456** [hyperledger/fabric-chaincode-go#47]
Why is it still used in official examples?

**Comment by bestbeforetoday** [comment]
shimtest has now been removed from [fabric-chaincode-go@v2.0.0](https://github.com/hyperledger/fabric-chaincode-go/releases/tag/v2.0.0). All the current samples (in the [fabric-samples](https://github.com/hyperledger/fabric-samples) repository) are using this version of fabric-chaincode-go and so shimtest should not be in use.
